controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# app_program_controller:
#     path: ../src/wildSeries/index.php
#     controller: App\Controller\ProgramController::index
